/* 
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Stardust.CoreSDK.Client;
using Stardust.CoreSDK.Model;

namespace Stardust.CoreSDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IGameEndpointsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Game
        /// </summary>
        /// <remarks>
        /// Get the Details of Your Game
        /// </remarks>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>SDGameGetResponse</returns>
        SDGameGetResponse GameGetGet ();

        /// <summary>
        /// Get Game
        /// </summary>
        /// <remarks>
        /// Get the Details of Your Game
        /// </remarks>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of SDGameGetResponse</returns>
        ApiResponse<SDGameGetResponse> GameGetGetWithHttpInfo ();
        /// <summary>
        /// Mutate Game
        /// </summary>
        /// <remarks>
        /// Change a games data
        /// </remarks>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Empty</returns>
        Empty GameMutatePut (SDGameMutateRequest body);

        /// <summary>
        /// Mutate Game
        /// </summary>
        /// <remarks>
        /// Change a games data
        /// </remarks>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Empty</returns>
        ApiResponse<Empty> GameMutatePutWithHttpInfo (SDGameMutateRequest body);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get Game
        /// </summary>
        /// <remarks>
        /// Get the Details of Your Game
        /// </remarks>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of SDGameGetResponse</returns>
        System.Threading.Tasks.Task<SDGameGetResponse> GameGetGetAsync ();

        /// <summary>
        /// Get Game
        /// </summary>
        /// <remarks>
        /// Get the Details of Your Game
        /// </remarks>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (SDGameGetResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SDGameGetResponse>> GameGetGetAsyncWithHttpInfo ();
        /// <summary>
        /// Mutate Game
        /// </summary>
        /// <remarks>
        /// Change a games data
        /// </remarks>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of Empty</returns>
        System.Threading.Tasks.Task<Empty> GameMutatePutAsync (SDGameMutateRequest body);

        /// <summary>
        /// Mutate Game
        /// </summary>
        /// <remarks>
        /// Change a games data
        /// </remarks>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (Empty)</returns>
        System.Threading.Tasks.Task<ApiResponse<Empty>> GameMutatePutAsyncWithHttpInfo (SDGameMutateRequest body);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class GameEndpointsApi : IGameEndpointsApi
    {
        private Stardust.CoreSDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="GameEndpointsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GameEndpointsApi(String basePath)
        {
            this.Configuration = new Stardust.CoreSDK.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Stardust.CoreSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GameEndpointsApi"/> class
        /// </summary>
        /// <returns></returns>
        public GameEndpointsApi()
        {
            this.Configuration = Stardust.CoreSDK.Client.Configuration.Default;

            ExceptionFactory = Stardust.CoreSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GameEndpointsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public GameEndpointsApi(Stardust.CoreSDK.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Stardust.CoreSDK.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Stardust.CoreSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Stardust.CoreSDK.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Stardust.CoreSDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get Game Get the Details of Your Game
        /// </summary>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>SDGameGetResponse</returns>
        public SDGameGetResponse GameGetGet ()
        {
             ApiResponse<SDGameGetResponse> localVarResponse = GameGetGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Game Get the Details of Your Game
        /// </summary>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of SDGameGetResponse</returns>
        public ApiResponse< SDGameGetResponse > GameGetGetWithHttpInfo ()
        {

            var localVarPath = "./game/get";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarHeaderParams["x-api-key"] = this.Configuration.GetApiKeyWithPrefix("x-api-key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GameGetGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SDGameGetResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (SDGameGetResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SDGameGetResponse)));
        }

        /// <summary>
        /// Get Game Get the Details of Your Game
        /// </summary>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of SDGameGetResponse</returns>
        public async System.Threading.Tasks.Task<SDGameGetResponse> GameGetGetAsync ()
        {
             ApiResponse<SDGameGetResponse> localVarResponse = await GameGetGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Game Get the Details of Your Game
        /// </summary>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (SDGameGetResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SDGameGetResponse>> GameGetGetAsyncWithHttpInfo ()
        {

            var localVarPath = "./game/get";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarHeaderParams["x-api-key"] = this.Configuration.GetApiKeyWithPrefix("x-api-key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GameGetGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SDGameGetResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (SDGameGetResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SDGameGetResponse)));
        }

        /// <summary>
        /// Mutate Game Change a games data
        /// </summary>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Empty</returns>
        public Empty GameMutatePut (SDGameMutateRequest body)
        {
             ApiResponse<Empty> localVarResponse = GameMutatePutWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Mutate Game Change a games data
        /// </summary>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Empty</returns>
        public ApiResponse< Empty > GameMutatePutWithHttpInfo (SDGameMutateRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling GameEndpointsApi->GameMutatePut");

            var localVarPath = "./game/mutate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarHeaderParams["x-api-key"] = this.Configuration.GetApiKeyWithPrefix("x-api-key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GameMutatePut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Empty>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (Empty) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Empty)));
        }

        /// <summary>
        /// Mutate Game Change a games data
        /// </summary>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of Empty</returns>
        public async System.Threading.Tasks.Task<Empty> GameMutatePutAsync (SDGameMutateRequest body)
        {
             ApiResponse<Empty> localVarResponse = await GameMutatePutAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Mutate Game Change a games data
        /// </summary>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (Empty)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Empty>> GameMutatePutAsyncWithHttpInfo (SDGameMutateRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling GameEndpointsApi->GameMutatePut");

            var localVarPath = "./game/mutate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarHeaderParams["x-api-key"] = this.Configuration.GetApiKeyWithPrefix("x-api-key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GameMutatePut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Empty>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (Empty) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Empty)));
        }

    }
}
