/* 
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Stardust.CoreSDK.Client;
using Stardust.CoreSDK.Model;

namespace Stardust.CoreSDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IHealthEndpointsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Health
        /// </summary>
        /// <remarks>
        /// Get system health info
        /// </remarks>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>SDHealthResponse</returns>
        SDHealthResponse HealthGet ();

        /// <summary>
        /// Get Health
        /// </summary>
        /// <remarks>
        /// Get system health info
        /// </remarks>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of SDHealthResponse</returns>
        ApiResponse<SDHealthResponse> HealthGetWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get Health
        /// </summary>
        /// <remarks>
        /// Get system health info
        /// </remarks>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of SDHealthResponse</returns>
        System.Threading.Tasks.Task<SDHealthResponse> HealthGetAsync ();

        /// <summary>
        /// Get Health
        /// </summary>
        /// <remarks>
        /// Get system health info
        /// </remarks>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (SDHealthResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SDHealthResponse>> HealthGetAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class HealthEndpointsApi : IHealthEndpointsApi
    {
        private Stardust.CoreSDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="HealthEndpointsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public HealthEndpointsApi(String basePath)
        {
            this.Configuration = new Stardust.CoreSDK.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Stardust.CoreSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HealthEndpointsApi"/> class
        /// </summary>
        /// <returns></returns>
        public HealthEndpointsApi()
        {
            this.Configuration = Stardust.CoreSDK.Client.Configuration.Default;

            ExceptionFactory = Stardust.CoreSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HealthEndpointsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public HealthEndpointsApi(Stardust.CoreSDK.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Stardust.CoreSDK.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Stardust.CoreSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Stardust.CoreSDK.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Stardust.CoreSDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get Health Get system health info
        /// </summary>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>SDHealthResponse</returns>
        public SDHealthResponse HealthGet ()
        {
             ApiResponse<SDHealthResponse> localVarResponse = HealthGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Health Get system health info
        /// </summary>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of SDHealthResponse</returns>
        public ApiResponse< SDHealthResponse > HealthGetWithHttpInfo ()
        {

            var localVarPath = "./health";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HealthGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SDHealthResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (SDHealthResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SDHealthResponse)));
        }

        /// <summary>
        /// Get Health Get system health info
        /// </summary>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of SDHealthResponse</returns>
        public async System.Threading.Tasks.Task<SDHealthResponse> HealthGetAsync ()
        {
             ApiResponse<SDHealthResponse> localVarResponse = await HealthGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Health Get system health info
        /// </summary>
        /// <exception cref="Stardust.CoreSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (SDHealthResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SDHealthResponse>> HealthGetAsyncWithHttpInfo ()
        {

            var localVarPath = "./health";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("HealthGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SDHealthResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (SDHealthResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SDHealthResponse)));
        }

    }
}
