/* 
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Stardust.CoreSDK.Client.SwaggerDateConverter;

namespace Stardust.CoreSDK.Model
{
    /// <summary>
    /// SDPlayerCreateRequest
    /// </summary>
    [DataContract]
        public partial class SDPlayerCreateRequest :  IEquatable<SDPlayerCreateRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SDPlayerCreateRequest" /> class.
        /// </summary>
        /// <param name="uniqueId">Identifier for the player (required).</param>
        /// <param name="image">URL of the player&#x27;s image.</param>
        /// <param name="userData">Metadata about the player (required).</param>
        public SDPlayerCreateRequest(string uniqueId = default(string), string image = default(string), Object userData = default(Object))
        {
            // to ensure "uniqueId" is required (not null)
            if (uniqueId == null)
            {
                throw new InvalidDataException("uniqueId is a required property for SDPlayerCreateRequest and cannot be null");
            }
            else
            {
                this.UniqueId = uniqueId;
            }
            // to ensure "userData" is required (not null)
            if (userData == null)
            {
                throw new InvalidDataException("userData is a required property for SDPlayerCreateRequest and cannot be null");
            }
            else
            {
                this.UserData = userData;
            }
            this.Image = image;
        }
        
        /// <summary>
        /// Identifier for the player
        /// </summary>
        /// <value>Identifier for the player</value>
        [DataMember(Name="uniqueId", EmitDefaultValue=false)]
        public string UniqueId { get; set; }

        /// <summary>
        /// URL of the player&#x27;s image
        /// </summary>
        /// <value>URL of the player&#x27;s image</value>
        [DataMember(Name="image", EmitDefaultValue=false)]
        public string Image { get; set; }

        /// <summary>
        /// Metadata about the player
        /// </summary>
        /// <value>Metadata about the player</value>
        [DataMember(Name="userData", EmitDefaultValue=false)]
        public Object UserData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SDPlayerCreateRequest {\n");
            sb.Append("  UniqueId: ").Append(UniqueId).Append("\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("  UserData: ").Append(UserData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SDPlayerCreateRequest);
        }

        /// <summary>
        /// Returns true if SDPlayerCreateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SDPlayerCreateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SDPlayerCreateRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UniqueId == input.UniqueId ||
                    (this.UniqueId != null &&
                    this.UniqueId.Equals(input.UniqueId))
                ) && 
                (
                    this.Image == input.Image ||
                    (this.Image != null &&
                    this.Image.Equals(input.Image))
                ) && 
                (
                    this.UserData == input.UserData ||
                    (this.UserData != null &&
                    this.UserData.Equals(input.UserData))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UniqueId != null)
                    hashCode = hashCode * 59 + this.UniqueId.GetHashCode();
                if (this.Image != null)
                    hashCode = hashCode * 59 + this.Image.GetHashCode();
                if (this.UserData != null)
                    hashCode = hashCode * 59 + this.UserData.GetHashCode();
                return hashCode;
            }
        }
    }
}
