/* 
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Stardust.CoreSDK.Client.SwaggerDateConverter;

namespace Stardust.CoreSDK.Model
{
    /// <summary>
    /// SDPlayerMutateRequest
    /// </summary>
    [DataContract]
        public partial class SDPlayerMutateRequest :  IEquatable<SDPlayerMutateRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SDPlayerMutateRequest" /> class.
        /// </summary>
        /// <param name="playerId">Can be found with Player/getId(s). (required).</param>
        /// <param name="props">Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7}) (required).</param>
        public SDPlayerMutateRequest(string playerId = default(string), Object props = default(Object))
        {
            // to ensure "playerId" is required (not null)
            if (playerId == null)
            {
                throw new InvalidDataException("playerId is a required property for SDPlayerMutateRequest and cannot be null");
            }
            else
            {
                this.PlayerId = playerId;
            }
            // to ensure "props" is required (not null)
            if (props == null)
            {
                throw new InvalidDataException("props is a required property for SDPlayerMutateRequest and cannot be null");
            }
            else
            {
                this.Props = props;
            }
        }
        
        /// <summary>
        /// Can be found with Player/getId(s).
        /// </summary>
        /// <value>Can be found with Player/getId(s).</value>
        [DataMember(Name="playerId", EmitDefaultValue=false)]
        public string PlayerId { get; set; }

        /// <summary>
        /// Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})
        /// </summary>
        /// <value>Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})</value>
        [DataMember(Name="props", EmitDefaultValue=false)]
        public Object Props { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SDPlayerMutateRequest {\n");
            sb.Append("  PlayerId: ").Append(PlayerId).Append("\n");
            sb.Append("  Props: ").Append(Props).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SDPlayerMutateRequest);
        }

        /// <summary>
        /// Returns true if SDPlayerMutateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SDPlayerMutateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SDPlayerMutateRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PlayerId == input.PlayerId ||
                    (this.PlayerId != null &&
                    this.PlayerId.Equals(input.PlayerId))
                ) && 
                (
                    this.Props == input.Props ||
                    (this.Props != null &&
                    this.Props.Equals(input.Props))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PlayerId != null)
                    hashCode = hashCode * 59 + this.PlayerId.GetHashCode();
                if (this.Props != null)
                    hashCode = hashCode * 59 + this.Props.GetHashCode();
                return hashCode;
            }
        }
    }
}
