/* 
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Stardust.CoreSDK.Client.SwaggerDateConverter;

namespace Stardust.CoreSDK.Model
{
    /// <summary>
    /// SDTemplateCreateRequest
    /// </summary>
    [DataContract]
        public partial class SDTemplateCreateRequest :  IEquatable<SDTemplateCreateRequest>
    {
        /// <summary>
        /// The type of custom contract to use for this template. Default will use a shared contract.
        /// </summary>
        /// <value>The type of custom contract to use for this template. Default will use a shared contract.</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum ContractTypeEnum
        {
            /// <summary>
            /// Enum ERC721 for value: ERC721
            /// </summary>
            [EnumMember(Value = "ERC721")]
            ERC721 = 1        }
        /// <summary>
        /// The type of custom contract to use for this template. Default will use a shared contract.
        /// </summary>
        /// <value>The type of custom contract to use for this template. Default will use a shared contract.</value>
        [DataMember(Name="contractType", EmitDefaultValue=false)]
        public ContractTypeEnum? ContractType { get; set; }
        /// <summary>
        /// FT is a currency where every instance is the same, NFT is where every token instance differes (ex. FT)
        /// </summary>
        /// <value>FT is a currency where every instance is the same, NFT is where every token instance differes (ex. FT)</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum TypeEnum
        {
            /// <summary>
            /// Enum FT for value: FT
            /// </summary>
            [EnumMember(Value = "FT")]
            FT = 1,
            /// <summary>
            /// Enum NFT for value: NFT
            /// </summary>
            [EnumMember(Value = "NFT")]
            NFT = 2        }
        /// <summary>
        /// FT is a currency where every instance is the same, NFT is where every token instance differes (ex. FT)
        /// </summary>
        /// <value>FT is a currency where every instance is the same, NFT is where every token instance differes (ex. FT)</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SDTemplateCreateRequest" /> class.
        /// </summary>
        /// <param name="name">The name of the template (ex. Bronze Axe) (required).</param>
        /// <param name="cap">u96 Number as String (ex. 200000000)  (required).</param>
        /// <param name="contractType">The type of custom contract to use for this template. Default will use a shared contract..</param>
        /// <param name="type">FT is a currency where every instance is the same, NFT is where every token instance differes (ex. FT) (required).</param>
        /// <param name="ownerAddress">Blockchain address to set as owner of the custom contract. Required if contractType is set..</param>
        /// <param name="props">props (required).</param>
        /// <param name="publicContractMetadata">Returned to marketplaces as contract metadata.</param>
        public SDTemplateCreateRequest(string name = default(string), string cap = default(string), ContractTypeEnum? contractType = default(ContractTypeEnum?), TypeEnum type = default(TypeEnum), string ownerAddress = default(string), SDTemplateCreateRequestProps props = default(SDTemplateCreateRequestProps), Object publicContractMetadata = default(Object))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for SDTemplateCreateRequest and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "cap" is required (not null)
            if (cap == null)
            {
                throw new InvalidDataException("cap is a required property for SDTemplateCreateRequest and cannot be null");
            }
            else
            {
                this.Cap = cap;
            }
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("type is a required property for SDTemplateCreateRequest and cannot be null");
            }
            else
            {
                this.Type = type;
            }
            // to ensure "props" is required (not null)
            if (props == null)
            {
                throw new InvalidDataException("props is a required property for SDTemplateCreateRequest and cannot be null");
            }
            else
            {
                this.Props = props;
            }
            this.ContractType = contractType;
            this.OwnerAddress = ownerAddress;
            this.PublicContractMetadata = publicContractMetadata;
        }
        
        /// <summary>
        /// The name of the template (ex. Bronze Axe)
        /// </summary>
        /// <value>The name of the template (ex. Bronze Axe)</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// u96 Number as String (ex. 200000000) 
        /// </summary>
        /// <value>u96 Number as String (ex. 200000000) </value>
        [DataMember(Name="cap", EmitDefaultValue=false)]
        public string Cap { get; set; }



        /// <summary>
        /// Blockchain address to set as owner of the custom contract. Required if contractType is set.
        /// </summary>
        /// <value>Blockchain address to set as owner of the custom contract. Required if contractType is set.</value>
        [DataMember(Name="ownerAddress", EmitDefaultValue=false)]
        public string OwnerAddress { get; set; }

        /// <summary>
        /// Gets or Sets Props
        /// </summary>
        [DataMember(Name="props", EmitDefaultValue=false)]
        public SDTemplateCreateRequestProps Props { get; set; }

        /// <summary>
        /// Returned to marketplaces as contract metadata
        /// </summary>
        /// <value>Returned to marketplaces as contract metadata</value>
        [DataMember(Name="publicContractMetadata", EmitDefaultValue=false)]
        public Object PublicContractMetadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SDTemplateCreateRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Cap: ").Append(Cap).Append("\n");
            sb.Append("  ContractType: ").Append(ContractType).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  OwnerAddress: ").Append(OwnerAddress).Append("\n");
            sb.Append("  Props: ").Append(Props).Append("\n");
            sb.Append("  PublicContractMetadata: ").Append(PublicContractMetadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SDTemplateCreateRequest);
        }

        /// <summary>
        /// Returns true if SDTemplateCreateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SDTemplateCreateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SDTemplateCreateRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Cap == input.Cap ||
                    (this.Cap != null &&
                    this.Cap.Equals(input.Cap))
                ) && 
                (
                    this.ContractType == input.ContractType ||
                    (this.ContractType != null &&
                    this.ContractType.Equals(input.ContractType))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.OwnerAddress == input.OwnerAddress ||
                    (this.OwnerAddress != null &&
                    this.OwnerAddress.Equals(input.OwnerAddress))
                ) && 
                (
                    this.Props == input.Props ||
                    (this.Props != null &&
                    this.Props.Equals(input.Props))
                ) && 
                (
                    this.PublicContractMetadata == input.PublicContractMetadata ||
                    (this.PublicContractMetadata != null &&
                    this.PublicContractMetadata.Equals(input.PublicContractMetadata))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Cap != null)
                    hashCode = hashCode * 59 + this.Cap.GetHashCode();
                if (this.ContractType != null)
                    hashCode = hashCode * 59 + this.ContractType.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.OwnerAddress != null)
                    hashCode = hashCode * 59 + this.OwnerAddress.GetHashCode();
                if (this.Props != null)
                    hashCode = hashCode * 59 + this.Props.GetHashCode();
                if (this.PublicContractMetadata != null)
                    hashCode = hashCode * 59 + this.PublicContractMetadata.GetHashCode();
                return hashCode;
            }
        }
    }
}
