/* 
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Stardust.CoreSDK.Client.SwaggerDateConverter;

namespace Stardust.CoreSDK.Model
{
    /// <summary>
    /// SDTemplateCreateBulkProps
    /// </summary>
    [DataContract]
        public partial class SDTemplateCreateBulkProps :  IEquatable<SDTemplateCreateBulkProps>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SDTemplateCreateBulkProps" /> class.
        /// </summary>
        /// <param name="immutable">Properties for immutable on the Template.</param>
        /// <param name="mutable">Properties for mutable on the Template.</param>
        /// <param name="mutable">Properties for mutable on the Item.</param>
        public SDTemplateCreateBulkProps(Object immutable = default(Object), Object mutable = default(Object), Object mutable = default(Object))
        {
            this.Immutable = immutable;
            this.Mutable = mutable;
            this.Mutable = mutable;
        }
        
        /// <summary>
        /// Properties for immutable on the Template
        /// </summary>
        /// <value>Properties for immutable on the Template</value>
        [DataMember(Name="immutable", EmitDefaultValue=false)]
        public Object Immutable { get; set; }

        /// <summary>
        /// Properties for mutable on the Template
        /// </summary>
        /// <value>Properties for mutable on the Template</value>
        [DataMember(Name="mutable", EmitDefaultValue=false)]
        public Object Mutable { get; set; }

        /// <summary>
        /// Properties for mutable on the Item
        /// </summary>
        /// <value>Properties for mutable on the Item</value>
        [DataMember(Name="$mutable", EmitDefaultValue=false)]
        public Object Mutable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SDTemplateCreateBulkProps {\n");
            sb.Append("  Immutable: ").Append(Immutable).Append("\n");
            sb.Append("  Mutable: ").Append(Mutable).Append("\n");
            sb.Append("  Mutable: ").Append(Mutable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SDTemplateCreateBulkProps);
        }

        /// <summary>
        /// Returns true if SDTemplateCreateBulkProps instances are equal
        /// </summary>
        /// <param name="input">Instance of SDTemplateCreateBulkProps to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SDTemplateCreateBulkProps input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Immutable == input.Immutable ||
                    (this.Immutable != null &&
                    this.Immutable.Equals(input.Immutable))
                ) && 
                (
                    this.Mutable == input.Mutable ||
                    (this.Mutable != null &&
                    this.Mutable.Equals(input.Mutable))
                ) && 
                (
                    this.Mutable == input.Mutable ||
                    (this.Mutable != null &&
                    this.Mutable.Equals(input.Mutable))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Immutable != null)
                    hashCode = hashCode * 59 + this.Immutable.GetHashCode();
                if (this.Mutable != null)
                    hashCode = hashCode * 59 + this.Mutable.GetHashCode();
                if (this.Mutable != null)
                    hashCode = hashCode * 59 + this.Mutable.GetHashCode();
                return hashCode;
            }
        }
    }
}
