/* 
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Stardust.CoreSDK.Client.SwaggerDateConverter;

namespace Stardust.CoreSDK.Model
{
    /// <summary>
    /// SDTokenBurnRequest
    /// </summary>
    [DataContract]
        public partial class SDTokenBurnRequest :  IEquatable<SDTokenBurnRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SDTokenBurnRequest" /> class.
        /// </summary>
        /// <param name="playerId">The Player&#x27;s id, can be found with Player/getId(s). (ex. CzySggxVQz51jciGRFDY7d5BER2fav6TNEnPGjusPJPd) (required).</param>
        /// <param name="tokenObjects">An an array of objects to burn (ex. [{tokenId: 5, amount: \&quot;6\&quot;}]) (required).</param>
        public SDTokenBurnRequest(string playerId = default(string), List<SDTokenBurnRequestTokenObjects> tokenObjects = default(List<SDTokenBurnRequestTokenObjects>))
        {
            // to ensure "playerId" is required (not null)
            if (playerId == null)
            {
                throw new InvalidDataException("playerId is a required property for SDTokenBurnRequest and cannot be null");
            }
            else
            {
                this.PlayerId = playerId;
            }
            // to ensure "tokenObjects" is required (not null)
            if (tokenObjects == null)
            {
                throw new InvalidDataException("tokenObjects is a required property for SDTokenBurnRequest and cannot be null");
            }
            else
            {
                this.TokenObjects = tokenObjects;
            }
        }
        
        /// <summary>
        /// The Player&#x27;s id, can be found with Player/getId(s). (ex. CzySggxVQz51jciGRFDY7d5BER2fav6TNEnPGjusPJPd)
        /// </summary>
        /// <value>The Player&#x27;s id, can be found with Player/getId(s). (ex. CzySggxVQz51jciGRFDY7d5BER2fav6TNEnPGjusPJPd)</value>
        [DataMember(Name="playerId", EmitDefaultValue=false)]
        public string PlayerId { get; set; }

        /// <summary>
        /// An an array of objects to burn (ex. [{tokenId: 5, amount: \&quot;6\&quot;}])
        /// </summary>
        /// <value>An an array of objects to burn (ex. [{tokenId: 5, amount: \&quot;6\&quot;}])</value>
        [DataMember(Name="tokenObjects", EmitDefaultValue=false)]
        public List<SDTokenBurnRequestTokenObjects> TokenObjects { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SDTokenBurnRequest {\n");
            sb.Append("  PlayerId: ").Append(PlayerId).Append("\n");
            sb.Append("  TokenObjects: ").Append(TokenObjects).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SDTokenBurnRequest);
        }

        /// <summary>
        /// Returns true if SDTokenBurnRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SDTokenBurnRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SDTokenBurnRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PlayerId == input.PlayerId ||
                    (this.PlayerId != null &&
                    this.PlayerId.Equals(input.PlayerId))
                ) && 
                (
                    this.TokenObjects == input.TokenObjects ||
                    this.TokenObjects != null &&
                    input.TokenObjects != null &&
                    this.TokenObjects.SequenceEqual(input.TokenObjects)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PlayerId != null)
                    hashCode = hashCode * 59 + this.PlayerId.GetHashCode();
                if (this.TokenObjects != null)
                    hashCode = hashCode * 59 + this.TokenObjects.GetHashCode();
                return hashCode;
            }
        }
    }
}
