/* 
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-22T22:32:07Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Stardust.CoreSDK.Client.SwaggerDateConverter;

namespace Stardust.CoreSDK.Model
{
    /// <summary>
    /// SDTokenMutateRequest
    /// </summary>
    [DataContract]
        public partial class SDTokenMutateRequest :  IEquatable<SDTokenMutateRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SDTokenMutateRequest" /> class.
        /// </summary>
        /// <param name="tokenId">Specifies which tokenId you want to manipulate (ex. 11) (required).</param>
        /// <param name="props">Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7}) (required).</param>
        /// <param name="publicMetadata">Returned to marketplaces as token metadata.</param>
        public SDTokenMutateRequest(int? tokenId = default(int?), Object props = default(Object), Object publicMetadata = default(Object))
        {
            // to ensure "tokenId" is required (not null)
            if (tokenId == null)
            {
                throw new InvalidDataException("tokenId is a required property for SDTokenMutateRequest and cannot be null");
            }
            else
            {
                this.TokenId = tokenId;
            }
            // to ensure "props" is required (not null)
            if (props == null)
            {
                throw new InvalidDataException("props is a required property for SDTokenMutateRequest and cannot be null");
            }
            else
            {
                this.Props = props;
            }
            this.PublicMetadata = publicMetadata;
        }
        
        /// <summary>
        /// Specifies which tokenId you want to manipulate (ex. 11)
        /// </summary>
        /// <value>Specifies which tokenId you want to manipulate (ex. 11)</value>
        [DataMember(Name="tokenId", EmitDefaultValue=false)]
        public int? TokenId { get; set; }

        /// <summary>
        /// Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})
        /// </summary>
        /// <value>Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})</value>
        [DataMember(Name="props", EmitDefaultValue=false)]
        public Object Props { get; set; }

        /// <summary>
        /// Returned to marketplaces as token metadata
        /// </summary>
        /// <value>Returned to marketplaces as token metadata</value>
        [DataMember(Name="publicMetadata", EmitDefaultValue=false)]
        public Object PublicMetadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SDTokenMutateRequest {\n");
            sb.Append("  TokenId: ").Append(TokenId).Append("\n");
            sb.Append("  Props: ").Append(Props).Append("\n");
            sb.Append("  PublicMetadata: ").Append(PublicMetadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SDTokenMutateRequest);
        }

        /// <summary>
        /// Returns true if SDTokenMutateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SDTokenMutateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SDTokenMutateRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TokenId == input.TokenId ||
                    (this.TokenId != null &&
                    this.TokenId.Equals(input.TokenId))
                ) && 
                (
                    this.Props == input.Props ||
                    (this.Props != null &&
                    this.Props.Equals(input.Props))
                ) && 
                (
                    this.PublicMetadata == input.PublicMetadata ||
                    (this.PublicMetadata != null &&
                    this.PublicMetadata.Equals(input.PublicMetadata))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TokenId != null)
                    hashCode = hashCode * 59 + this.TokenId.GetHashCode();
                if (this.Props != null)
                    hashCode = hashCode * 59 + this.Props.GetHashCode();
                if (this.PublicMetadata != null)
                    hashCode = hashCode * 59 + this.PublicMetadata.GetHashCode();
                return hashCode;
            }
        }
    }
}
